### PR TITLE
Fix type for labelled

### PR DESCRIPTION
**Pull request by kylef**

### CODE REVIEW

**Comment by kylef** [comment]
Whoops, just realised "facilitate" is a word, in the American dictionary. Undone that change.

**Comment by thii** [comment]
"Labeled" and "unlabeled" are in the American dictionary too. I assume this is a joke, right?

**Comment by lattner** [comment]
unlabeled is also an american english word.

**Comment by kylef** [comment]
My bad, I wasn't aware you could spell them without the double-l in American.

**Pull request closed without merging**
